Fix mismatched delete/free in OSQPModel
tesseract-robotics/trajopt pull request #398
Opened 2024-04-10 12:56 UTC by Jack-ReframeSystems

Previously we were calling delete on the CSC matrix pointer but its malloc'd, we should be calling "free" instead. We also don't want to free any of the subfield (using something like `csc_spfree`) since we manage the individual fields in OSQPModel vectors.

2024-04-12 12:48 UTC, Levi-Armstrong requested changes
LGTM, Could can you run clang format? There is a script .run-clang-format that you may run.

2024-04-12 21:08 UTC, Jack-ReframeSystems commented
> LGTM, Could can you run clang format? There is a script .run-clang-format that you may run.

Do you mind if I change the clang format script to use a newer version of clang? Its using clang 8 at the moment but I can't get that on Ubuntu Jammy, I would like to change it to use the clang default version on the system. 

I'll update the PR with this and you can let me know if you have concerns with this.

2024-04-13 01:41 UTC, Levi-Armstrong commented on .run-clang-format
> -find . -type f -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\|hxx\)' -exec clang-format-8 -style=file -i {} \;
Just for consistency please revert change.

2024-04-13 01:53 UTC, Levi-Armstrong commented
replaced by #399

2024-04-13 01:53 UTC, closed without merging

2024-04-30 15:22 UTC, rjoomen commented
Good catch!